services:
  main:
    image: engineering.sanya.gay/pluralflux/pluralflux
    container_name: pluralflux
    restart: unless-stopped
    networks:
      - pluralflux-net
    env_file: "variables.env"
  postgres:
    image: postgres:latest
    container_name: pluralflux-postgres
    env_file: "variables.env"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./pgBackup:/mnt/pgBackup
    networks:
      - pluralflux-net
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pluralflux-pgadmin
    ports:
      - "5050:80"
    env_file: "variables.env"
    depends_on:
      - postgres
    networks:
      - pluralflux-net
    volumes:
      - pgadmindata:/var/lib/pgadmin
      #- ./pgBackup:/mnt/host
      # uncomment the above line if you plan to restore / backup dump files from PGAdmin UI
networks:
  pluralflux-net:
    driver: bridge

volumes:
  pgdata:
  pgadmindata:
